INSERT INTO books (name, year, pages, description, views, wanted, deleted) VALUES
('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА',2003,351,'Лекции и практикум по программированию на Си++',0,0,0),
('Программирование на языке Go!',2010,290,'Лекции и практикум по программированию на Go!',0,0,0),
('Толковый словарь сетевых терминов и аббревиатур',2007,410,'Толковый словарь сетевых терминов и аббревиатур',0,0,0),
('Python for Data Analysis',2011,327,'Python for Data Analysis and so on',0,0,0),
('Thinking in Java (4th Edition)',2000,378,'Лекции и практикум по программированию на Java',0,0,0),
('Introduction to Algorithms',2005,315,'Книга для развития алгоритмического мышления',0,0,0),
('JavaScript Pocket Reference',2012,263,'Краткое руководство по JavaScript',0,0,0),
('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles',2006,336,'Лекции и практикум по программированию на С#',0,0,0),
('SQL: The Complete Reference',2009,348,'Полное руководство по SQL',0,0,0),
('PHP and MySQL Web Development',2011,405,'Разработка при помощи PHP и SQL',0,0,0),
('Статистический анализ и визуализация данных с помощью R',2013,338,'Статистический анализ и визуализация данных с помощью R (что бы это ни было)',0,0,0),
('Computer Coding for Kid',2015,235,'Программирование для детей',0,0,0),
('Exploring Arduino: Tools and Techniques for Engineering Wizardry',2017,277,'Руководство по Arduino для начинающих',0,0,0),
('Программирование микроконтроллеров для начинающих и не только',2014,364,'Руководство по программированию микроконтроллеров',0,0,0),
('The Internet of Things',2018,249,'Что такое интернет и нафига он нужен',0,0,0),
('Sketching User Experiences: The Workbook',2017,268,'Вообще не понятно что это и для чего',0,0,0),
('InDesign CS6',2013,208,'Руководство пользователя InDesign',0,0,0),
('Адаптивный дизайн. Делаем сайты для любых устройств',2015,293,'Настольная книга фронтэндщика',0,0,0),
('Android для разработчиков',2019,315,'Разработка для устройств Android',0,0,0),
('Clean Code: A Handbook of Agile Software Craftsmanship',2015,339,'Как не писать говнокод',0,0,0),
('Swift Pocket Reference: Programming for iOS and OS X',2020,377,'Разработка для устройств на базе iOS and OS X',0,0,0),
('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence',2009,375,'Видимо что-то по SQL',0,0,0),
('Head First Ruby',2019,329,'Руководство по Ruby для чайников',0,0,0),
('Practical Vim',2012,267,'Вообще не понятно что это и для чего',0,0,0);