version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: swdb
    healthcheck:
            test: mysql swdb --user=root --password='administrator' --silent --execute "SELECT 1;"
            interval: 3s
            timeout: 1s
            retries: 10

  app:
    build: .
    depends_on:
        migrations:
          condition: service_completed_successfully
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  
  migrations: 
    image: 42-app
    command: sh -c 'npm run migration:run'
    depends_on:
      db:
        condition: service_healthy