version: '3.1'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    tty: true
    networks:
      - swapi_network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - swapi_network
    tty: true

  app:
    build: .
    networks:
      - swapi_network
    depends_on:
      - db
    tty: true
  
networks:
  swapi_network:
    driver: bridge