version: '3.1'
services:
  mysqldb:
    container_name: library
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080